# Generated by Django 5.1.2 on 2024-10-28 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_rename_vendor_fooditem_vendor'),
        ('vendor', '0003_alter_vendor_vendor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fooditems', to='menu.category'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fooditems', to='vendor.vendor'),
        ),
    ]
