# Generated by Django 5.1.2 on 2024-11-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_total_data'),
        ('vendor', '0008_alter_openinghour_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vendors',
            field=models.ManyToManyField(blank=True, related_name='orders', to='vendor.vendor'),
        ),
    ]
